#!/usr/bin/env node
// Sync canonical role/protocol files from the repo root into the Docusaurus
// docs site (website/docs/reference/) so the docs site never hand-copies them.
// Sibling of sync-role-templates.mjs. Idempotent. Fails loudly if a source is
// missing. The reference/ directory is gitignored — it is generated, not authored.

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Canonical sources at the repo root, in sidebar order. Each becomes one
// generated Markdown page under website/docs/reference/.
const SOURCES = [
  { file: "TASK_ANALYZER_ROLE.md", label: "/task-analyze" },
  { file: "TASKMASTER_ROLE.md", label: "/taskmaster" },
  { file: "TASKMASTER_CHANGE_ROLE.md", label: "/taskmaster-change" },
  { file: "TASK_IMPLEMENTER_ROLE.md", label: "/task-implement" },
  { file: "TASK_REVIEWER_ROLE.md", label: "/task-review" },
  { file: "TASK_REVIEW_FIXER_ROLE.md", label: "/task-review-fix" },
  { file: "TASK_HUMAN_REVIEW_ROLE.md", label: "/task-human-review" },
  { file: "TASK_REQUEST_CHANGES_ROLE.md", label: "/task-request-changes" },
  { file: "TASK_INCIDENT_ROLE.md", label: "/task-incident" },
  { file: "TASK_GIT_ROLE.md", label: "/task-git" },
  { file: "AGENT_PROTOCOL.md", label: "Agent protocol" },
  { file: "AGENT_ENFORCEMENT.md", label: "Agent enforcement" },
  { file: "AGENT_SECURITY.md", label: "Agent security" },
  { file: "AGENT_CONFIG.md", label: "Agent config" },
  { file: "AGENT_NOTIFY.md", label: "Agent notify" },
  { file: "PR_API.md", label: "PR API examples" },
];

const __filename = fileURLToPath(import.meta.url);
const packageRoot = resolve(dirname(__filename), "..");
const repoRoot = resolve(packageRoot, "..", "..");
const destDir = resolve(repoRoot, "website", "docs", "reference");

// Strip a leading YAML frontmatter block from the source so it can't collide
// with the frontmatter we inject. (Current sources have none, but be safe.)
function stripFrontmatter(content) {
  if (!content.startsWith("---")) return content;
  const end = content.indexOf("\n---", 3);
  if (end === -1) return content;
  const after = content.indexOf("\n", end + 1);
  return after === -1 ? "" : content.slice(after + 1);
}

function docIdFor(file) {
  return file.replace(/\.md$/, "");
}

function pageFor({ file, label }, position) {
  const src = resolve(repoRoot, file);
  const raw = readFileSync(src, "utf-8");
  const body = stripFrontmatter(raw).replace(/^\n+/, "");
  const frontmatter = [
    "---",
    `title: ${file}`,
    `sidebar_label: ${label}`,
    `sidebar_position: ${position}`,
    `description: Reference copy of ${file}, generated from the repo root.`,
    "---",
    "",
  ].join("\n");
  const banner = [
    "<!--",
    "  AUTO-GENERATED FILE — DO NOT EDIT.",
    `  Source of truth: ${file} at the repository root.`,
    "  Regenerate with: pnpm --dir website sync",
    "-->",
    "",
    `> **Reference copy.** Generated from \`${file}\` at the repository root.`,
    "> Edit the source file, not this copy.",
    "",
  ].join("\n");
  return frontmatter + banner + body;
}

const indexPage = [
  "---",
  "title: Reference",
  "sidebar_label: Overview",
  "sidebar_position: 0",
  "description: Canonical agent role and protocol files, synced from the repo root.",
  "---",
  "",
  "<!-- AUTO-GENERATED FILE — DO NOT EDIT. Regenerate with: pnpm --dir website sync -->",
  "",
  "# Reference",
  "",
  "These pages are **generated** from the canonical agent role and protocol",
  "files at the repository root by `packages/taskflow/scripts/sync-docs.mjs`.",
  "They are the source of truth for the slash-command workflow — edit the root",
  "files, not these copies.",
  "",
  ...SOURCES.map(({ file, label }) => `- [\`${file}\`](./${file}) — ${label}`),
  "",
].join("\n");

// Idempotent write: only touch a file when its content actually changes.
function writeIfChanged(path, content) {
  const prev = existsSync(path) ? readFileSync(path, "utf-8") : null;
  if (prev === content) return false;
  writeFileSync(path, content, "utf-8");
  return true;
}

mkdirSync(destDir, { recursive: true });

// Category metadata so the generated folder slots into the autogenerated sidebar.
const categoryJson =
  JSON.stringify(
    {
      label: "Reference (synced)",
      position: 6,
      collapsible: true,
      collapsed: true,
      link: { type: "doc", id: "reference/index" },
    },
    null,
    2,
  ) + "\n";

let written = 0;
let unchanged = 0;
const missing = [];
const expected = new Set(["index.md", "_category_.json"]);

for (const [i, source] of SOURCES.entries()) {
  const src = resolve(repoRoot, source.file);
  if (!existsSync(src)) {
    missing.push(source.file);
    continue;
  }
  const outName = `${docIdFor(source.file)}.md`;
  expected.add(outName);
  const changed = writeIfChanged(resolve(destDir, outName), pageFor(source, i + 1));
  changed ? written++ : unchanged++;
}

if (writeIfChanged(resolve(destDir, "index.md"), indexPage)) written++;
else unchanged++;

if (writeIfChanged(resolve(destDir, "_category_.json"), categoryJson)) written++;
else unchanged++;

// Prune stale generated files (a source removed from SOURCES).
let pruned = 0;
for (const name of readdirSync(destDir)) {
  if (!expected.has(name)) {
    rmSync(resolve(destDir, name));
    pruned++;
  }
}

console.log(JSON.stringify({ action: "sync-docs", written, unchanged, pruned, missing }));

if (missing.length > 0) {
  process.exitCode = 1;
}
