import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Single autogenerated sidebar driven by the docs/ folder structure.
 * Ordering + labels come from each folder's `_category_.json` and each page's
 * `sidebar_position` frontmatter. The `reference/` category is generated at
 * build time by `packages/taskflow/scripts/sync-docs.mjs` (gitignored), which
 * also emits its `_category_.json`.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
